// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxGMWdImU90iPi9MKjxs_b8gTQX8wyyNY',
    appId: '1:766032199812:web:7acb9795fdc14a45bec2d1',
    messagingSenderId: '766032199812',
    projectId: 'notes-app-72243',
    authDomain: 'notes-app-72243.firebaseapp.com',
    storageBucket: 'notes-app-72243.appspot.com',
    measurementId: 'G-L9K90BDPYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoUBn6Yc7fBq2O8tz6jv5_PEV4pg-1dJ4',
    appId: '1:766032199812:android:adebdd8ff9d25adfbec2d1',
    messagingSenderId: '766032199812',
    projectId: 'notes-app-72243',
    storageBucket: 'notes-app-72243.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuyCRARS4mawwAD_r0tiZHzX4rCsXxp3g',
    appId: '1:766032199812:ios:4c05d86ff49a449ebec2d1',
    messagingSenderId: '766032199812',
    projectId: 'notes-app-72243',
    storageBucket: 'notes-app-72243.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuyCRARS4mawwAD_r0tiZHzX4rCsXxp3g',
    appId: '1:766032199812:ios:4c05d86ff49a449ebec2d1',
    messagingSenderId: '766032199812',
    projectId: 'notes-app-72243',
    storageBucket: 'notes-app-72243.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxGMWdImU90iPi9MKjxs_b8gTQX8wyyNY',
    appId: '1:766032199812:web:e418e1bf00efcaadbec2d1',
    messagingSenderId: '766032199812',
    projectId: 'notes-app-72243',
    authDomain: 'notes-app-72243.firebaseapp.com',
    storageBucket: 'notes-app-72243.appspot.com',
    measurementId: 'G-277FBZB120',
  );
}
